ANIM_ML_TO_HEIGHT_SCALE: float = 0.02

ANIM_CONTAINER_SHAKER_W_TOP: float = 2.2
ANIM_CONTAINER_SHAKER_W_BOT: float = 1.7
ANIM_CONTAINER_SHAKER_HEIGHT: float = 3.4
ANIM_CONTAINER_MIXING_W_TOP: float = 2.3
ANIM_CONTAINER_MIXING_W_BOT: float = 2.0
ANIM_CONTAINER_MIXING_HEIGHT: float = 3.2
ANIM_CONTAINER_STEMMED_W_TOP: float = 2.8
ANIM_CONTAINER_STEMMED_W_BOT: float = 0.4
ANIM_CONTAINER_STEMMED_HEIGHT: float = 1.8
ANIM_CONTAINER_TALL_W_TOP: float = 1.8
ANIM_CONTAINER_TALL_W_BOT: float = 1.6
ANIM_CONTAINER_TALL_HEIGHT: float = 3.6
ANIM_CONTAINER_ROCKS_W_TOP: float = 2.4
ANIM_CONTAINER_ROCKS_W_BOT: float = 2.0
ANIM_CONTAINER_ROCKS_HEIGHT: float = 2.4
ANIM_CONTAINER_OUTLINE_STROKE_WIDTH: float = 4.0
ANIM_CONTAINER_STEM_LENGTH: float = 1.0
ANIM_CONTAINER_STEM_BASE_HALF_WIDTH: float = 0.8
ANIM_CONTAINER_LABEL_FONT_SIZE: int = 15
ANIM_CONTAINER_LABEL_BUFF: float = 0.25
ANIM_LAYER_DEFAULT_OPACITY: float = 0.92

ANIM_VESSEL_Y_OFFSET: float = 0.9
ANIM_VESSEL_PAIR_X_OFFSET: float = 2.5
ANIM_VESSEL_CREATE_RUN_TIME: float = 0.5

ANIM_TITLE_FONT_SIZE: int = 36
ANIM_TITLE_BUFF: float = 0.35
ANIM_COLOR_DEFAULT_INGREDIENT: str = "#FFFFFF"
ANIM_INGREDIENT_DOT_RADIUS: float = 0.06
ANIM_INGREDIENT_FONT_SIZE_NORMAL: int = 15
ANIM_INGREDIENT_FONT_SIZE_COMPACT: int = 13
ANIM_INGREDIENT_COMPACT_THRESHOLD: int = 6
ANIM_INGREDIENT_ENTRY_BUFF: float = 0.12
ANIM_INGREDIENT_LIST_BUFF_NORMAL: float = 0.14
ANIM_INGREDIENT_LIST_BUFF_COMPACT: float = 0.10
ANIM_INGREDIENT_PANEL_BUFF: float = 0.35

ANIM_STEP_WRAP_WORDS_PER_LINE: int = 6
ANIM_STEP_TITLE_FONT_SIZE: int = 25
ANIM_STEP_TITLE_Y: float = 2.1
ANIM_STEP_DESC_FONT_SIZE: int = 17
ANIM_STEP_DESC_LINE_SPACING: float = 1.1
ANIM_STEP_DESC_BUFF: float = 0.15
ANIM_STEP_TRANSFORM_RUN_TIME: float = 0.45

ANIM_CHILL_FROST_STROKE_WIDTH: float = 6.0
ANIM_CHILL_FROST_STROKE_OPACITY: float = 0.7
ANIM_CHILL_FADE_TARGET_OPACITY: float = 0.15

ANIM_COLOR_ICE: str = "#D4E6F1"
ANIM_ICE_STROKE_WIDTH: float = 1.5
ANIM_ICE_SPHERE_RADIUS: float = 0.45
ANIM_ICE_ROCK_SIZE: float = 0.9
ANIM_ICE_ROCK_CORNER_RADIUS: float = 0.1
ANIM_ICE_LARGE_FILL_OPACITY: float = 0.8
ANIM_ICE_LARGE_Y_OFFSET: float = 0.5
ANIM_ICE_LARGE_HEIGHT_DELTA: float = 0.95
ANIM_ICE_CUBE_COUNT_PREP: int = 3
ANIM_ICE_CUBE_COUNT_SERVING: int = 2
ANIM_ICE_CUBE_SIZE: float = 0.42
ANIM_ICE_CUBE_CORNER_RADIUS: float = 0.08
ANIM_ICE_CUBE_FILL_OPACITY: float = 0.85
ANIM_ICE_CUBE_X_SPACING: float = 0.35
ANIM_ICE_CUBE_Y_OFFSET: float = 0.25
ANIM_ICE_CUBE_HEIGHT_DELTA: float = 0.45
ANIM_SOLIDS_Z_INDEX: int = 10

ANIM_COLOR_DEFAULT_LIQUID: str = "#E9F1F5"
ANIM_MEASURE_DEFAULT_AMOUNT_ML: float = 20.0
ANIM_MEASURE_DASH_HEIGHT_SCALE: float = 0.03
ANIM_MEASURE_MAX_FILL_MARGIN: float = 0.15
ANIM_MEASURE_MIN_AVAILABLE_HEIGHT: float = 0.1
ANIM_MEASURE_TOP_MARGIN: float = 0.20
ANIM_MEASURE_TOP_MIN_THICKNESS: float = 0.4
ANIM_MEASURE_FALLBACK_THICKNESS: float = 0.4
ANIM_MEASURE_STREAM_START_OFFSET: float = 1.2
ANIM_MEASURE_STREAM_STROKE_WIDTH_LIQUID: float = 3.5
ANIM_MEASURE_STREAM_STROKE_WIDTH_OTHER: float = 2.0
ANIM_MEASURE_STREAM_Z_INDEX: int = 5
ANIM_SOLID_LEAF_WIDTH: float = 0.4
ANIM_SOLID_LEAF_HEIGHT: float = 0.22
ANIM_SOLID_LEAF_FILL_OPACITY: float = 0.9
ANIM_SOLID_SQUARE_SIDE: float = 0.32
ANIM_SOLID_SQUARE_FILL_OPACITY: float = 0.95
ANIM_SOLID_STROKE_WIDTH: float = 1.0
ANIM_SOLID_Y_OFFSET: float = 0.2
ANIM_SOLID_HEIGHT_DELTA: float = 0.35

ANIM_COLOR_DEFAULT_SHAKE_BLEND: str = "#E59866"
ANIM_SHAKE_WIGGLE_ROTATION: float = 0.12
ANIM_SHAKE_WIGGLE_COUNT: int = 6
ANIM_SHAKE_WIGGLE_RUN_TIME: float = 1.0

ANIM_COLOR_DEFAULT_MUDDLE_BLEND: str = "#C86D27"
ANIM_COLOR_MUDDLER_WOOD_DARK: str = "#5D4037"
ANIM_COLOR_MUDDLER_WOOD_DARKEST: str = "#3E2723"
ANIM_COLOR_MUDDLER_WOOD_LIGHT: str = "#795548"
ANIM_COLOR_MUDDLER_WOOD_MEDIUM: str = "#4E342E"
ANIM_MUDDLER_HEAD_HEIGHT: float = 0.55
ANIM_MUDDLER_HEAD_WIDTH: float = 0.44
ANIM_MUDDLER_HEAD_CORNER_RADIUS: float = 0.06
ANIM_MUDDLER_STROKE_WIDTH: float = 1.5
ANIM_MUDDLER_HANDLE_WIDTH: float = 0.22
ANIM_MUDDLER_HANDLE_CORNER_RADIUS: float = 0.07
ANIM_MUDDLER_HANDLE_MIN_HEIGHT: float = 2.7
ANIM_MUDDLER_HANDLE_HEIGHT_PADDING: float = 0.8
ANIM_MUDDLER_POMMEL_RADIUS: float = 0.15
ANIM_TOOL_Z_INDEX: int = 15
ANIM_MUDDLE_MIN_HEIGHT: float = 0.25

ANIM_COLOR_DEFAULT_STIR_BLEND: str = "#C86D27"
ANIM_COLOR_SPOON_METAL_LIGHT: str = "#ECEFF1"
ANIM_COLOR_SPOON_METAL_DARK: str = "#90A4AE"
ANIM_COLOR_SPOON_INNER: str = "#CFD8DC"
ANIM_COLOR_SPOON_KNOB: str = "#B0BEC5"
ANIM_COLOR_SPOON_KNOB_STROKE: str = "#78909C"
ANIM_SPOON_BOWL_WIDTH: float = 0.28
ANIM_SPOON_BOWL_HEIGHT: float = 0.42
ANIM_SPOON_INNER_WIDTH: float = 0.18
ANIM_SPOON_INNER_HEIGHT: float = 0.30
ANIM_SPOON_INNER_OPACITY: float = 0.6
ANIM_SPOON_KNOB_RADIUS: float = 0.09
ANIM_SPOON_STROKE_WIDTH: float = 1.5
ANIM_SPOON_STEM_STROKE_WIDTH: float = 3.5
ANIM_SPOON_STEM_HEIGHT_PADDING: float = 1.0
ANIM_SPOON_SPIRAL_COUNT: int = 6
ANIM_SPOON_SPIRAL_MARGIN: float = 0.4
ANIM_SPOON_SPIRAL_X_OFFSET: float = 0.04
ANIM_SPOON_SPIRAL_Y_STEP: float = 0.08
ANIM_STIR_ORBIT_RADIUS_RATIO: float = 0.22
ANIM_STIR_ORBIT_RY: float = 0.04
ANIM_STIR_ORBIT_Y_OFFSET: float = 0.18
ANIM_STIR_ORBIT_ANGLE_PI_MULTIPLIER: float = 4.0
ANIM_STIR_ORBIT_RUN_TIME: float = 1.4
ANIM_STIR_SOLIDS_ROTATE: float = 0.3

ANIM_COLOR_DEFAULT_STRAIN: str = "#E59866"
ANIM_COLOR_FOAM: str = "#FFFFFF"
ANIM_STRAIN_RIM_MARGIN: float = 0.15
ANIM_STRAIN_FOAM_THICKNESS: float = 0.45
ANIM_STRAIN_FOAM_MIN_LIQUID_THICKNESS: float = 0.6
ANIM_STRAIN_TILT_ANGLE: float = 0.42
ANIM_STRAIN_TILT_RUN_TIME: float = 0.45
ANIM_STRAIN_POUR_STROKE_WIDTH: float = 4.5
ANIM_STRAIN_FOAM_Z_INDEX: int = 13
ANIM_STRAIN_TRANSFER_RUN_TIME: float = 0.75
ANIM_STRAIN_TILT_BACK_RUN_TIME: float = 0.40

ANIM_COLOR_DEFAULT_GARNISH: str = "#FFA500"
ANIM_GARNISH_DEFAULT_SHAPE: str = "half circle"
ANIM_GARNISH_STROKE_WIDTH: float = 1.0
ANIM_GARNISH_LEAF_WIDTH: float = 0.42
ANIM_GARNISH_LEAF_HEIGHT: float = 0.22
ANIM_GARNISH_HALF_CIRCLE_INNER_RADIUS: float = 0.15
ANIM_GARNISH_HALF_CIRCLE_OUTER_RADIUS: float = 0.38
ANIM_GARNISH_TRIANGLE_SCALE: float = 0.25
ANIM_GARNISH_DASH_RADIUS: float = 0.08
ANIM_GARNISH_DASH_BUFF: float = 0.12
ANIM_GARNISH_FOAM_HEIGHT: float = 0.2
ANIM_GARNISH_FOAM_WIDTH_RATIO: float = 0.85
ANIM_GARNISH_FOAM_OPACITY: float = 0.95
ANIM_GARNISH_SURFACE_Y_OFFSET: float = 0.1
ANIM_GARNISH_SIDE_OFFSET: float = 0.45
ANIM_GARNISH_Z_INDEX: int = 20
ANIM_GARNISH_FADE_RUN_TIME: float = 0.4

ANIM_DEFAULT_STEP_WAIT_S: float = 0.15
ANIM_FINAL_WAIT_S: float = 0.6
ANIM_ICE_CUBE_LAG_RATIO: float = 0.15

ANIM_DEFAULT_COCKTAIL_NAME: str = "Cocktail"
ANIM_DEFAULT_GLASS_TYPE: str = "rocks"
ANIM_LABEL_SERVING_GLASS: str = "Serving Glass"
ANIM_LABEL_SHAKER: str = "Shaker"
ANIM_LABEL_MIXING_GLASS: str = "Mixing Glass"

ANIM_TITLE_FADE_SHIFT: float = 0.3
ANIM_TITLE_FADE_RUN_TIME: float = 0.5
ANIM_INGREDIENT_LIST_FADE_SHIFT: float = 0.3
ANIM_INGREDIENT_LIST_FADE_RUN_TIME: float = 0.6

ANIM_CHILL_FADE_IN_RUN_TIME: float = 0.4
ANIM_CHILL_FADE_OUT_RUN_TIME: float = 0.3

ANIM_ICE_LARGE_FADE_SHIFT: float = 0.8
ANIM_ICE_LARGE_FADE_RUN_TIME: float = 0.35
ANIM_ICE_CUBE_FADE_SHIFT: float = 0.6
ANIM_ICE_CUBE_FADE_RUN_TIME: float = 0.25

ANIM_MEASURE_STREAM_CREATE_RUN_TIME: float = 0.20
ANIM_MEASURE_LAYER_FADE_SHIFT: float = 0.05
ANIM_MEASURE_LAYER_FADE_RUN_TIME: float = 0.35
ANIM_MEASURE_STREAM_FADE_RUN_TIME: float = 0.15
ANIM_SOLID_FADE_SHIFT: float = 0.8
ANIM_SOLID_FADE_RUN_TIME: float = 0.35

ANIM_SHAKE_WIGGLE_SCALE: float = 1.0
ANIM_SHAKE_MERGE_RUN_TIME: float = 0.45

ANIM_MUDDLER_GROOVE_INSET: float = 0.05
ANIM_MUDDLER_GROOVE_DROP: float = 0.08
ANIM_MUDDLER_HANDLE_OVERLAP: float = 0.08
ANIM_MUDDLER_POMMEL_OVERLAP: float = 0.06
ANIM_MUDDLER_BOTTOM_OFFSET: float = 0.05
ANIM_MUDDLER_FADE_IN_SHIFT: float = 1.0
ANIM_MUDDLER_FADE_IN_RUN_TIME: float = 0.35
ANIM_MUDDLER_FADE_OUT_SHIFT: float = 0.9
ANIM_MUDDLER_FADE_OUT_RUN_TIME: float = 0.3
ANIM_MUDDLER_STROKE_RUN_TIME: float = 0.25
ANIM_MUDDLER_STROKES: tuple[tuple[float, float], ...] = ((-0.05, 0.20), (0.15, -0.40), (-0.10, 0.20))
ANIM_MUDDLE_MERGE_RUN_TIME: float = 0.40

ANIM_SPOON_INNER_X_SHIFT: float = 0.03
ANIM_SPOON_KNOB_STROKE_WIDTH: float = 1.0
ANIM_SPOON_FADE_IN_SHIFT: float = 0.8
ANIM_SPOON_FADE_IN_RUN_TIME: float = 0.35
ANIM_SPOON_FADE_OUT_SHIFT: float = 0.8
ANIM_SPOON_FADE_OUT_RUN_TIME: float = 0.25
ANIM_STIR_MERGE_RUN_TIME: float = 0.40

ANIM_STRAIN_FOAM_OPACITY: float = 1.0
ANIM_STRAIN_LAYER_FADE_SHIFT: float = 0.15
ANIM_STRAIN_FOAM_FADE_SHIFT: float = 0.12
ANIM_STRAIN_POUR_CREATE_RUN_TIME: float = 0.20
ANIM_STRAIN_POUR_FADE_RUN_TIME: float = 0.15
ANIM_STRAIN_POUR_START_OFFSET: tuple[float, float] = (0.05, -0.05)
ANIM_STRAIN_POUR_CONTROL_1_OFFSET: tuple[float, float] = (0.55, 0.35)
ANIM_STRAIN_POUR_CONTROL_2_OFFSET: tuple[float, float] = (-0.45, 0.65)

ANIM_GARNISH_FOAM_CORNER_RADIUS: float = 0.1
ANIM_GARNISH_FADE_SHIFT: float = 0.3

ANIM_FINALE_FADE_RUN_TIME: float = 0.4
