ORG_NAME: str = "Lloyd"
APP_NAME: str = "Lloyd"

WINDOW_TITLE: str = "Lloyd"
WINDOW_MIN_WIDTH: int = 1024
WINDOW_MIN_HEIGHT: int = 640

SPLITTER_HANDLE_WIDTH: int = 4
SPLITTER_STRETCH_CANVAS: int = 3
SPLITTER_STRETCH_CHAT: int = 1
SPLITTER_DEFAULT_CANVAS_RATIO: float = 0.75
SPLITTER_DEFAULT_CHAT_RATIO: float = 0.25

FULLSCREEN_SHORTCUT_F11: str = "F11"
FULLSCREEN_SHORTCUT_ESC: str = "Esc"

SETTINGS_SPLITTER_STATE_KEY: str = "window/splitter_state"
SETTINGS_VOLUME_KEY: str = "audio/volume_percent"
SETTINGS_WINDOW_GROUP: str = "window"
SETTINGS_GEOMETRY_LEAF: str = "geometry"
SETTINGS_WINDOW_STATE_LEAF: str = "state"
SETTINGS_SCREEN_NAME_LEAF: str = "screen_name"
SETTINGS_SCREEN_RECT_LEAF: str = "screen_rect"
SETTINGS_NORMAL_RECT_LEAF: str = "normal_rect"

WINDOW_STATE_NORMAL: str = "normal"
WINDOW_STATE_MAXIMIZED: str = "maximized"
WINDOW_STATE_FULLSCREEN: str = "fullscreen"
WINDOW_STATES: frozenset[str] = frozenset({WINDOW_STATE_NORMAL, WINDOW_STATE_MAXIMIZED, WINDOW_STATE_FULLSCREEN})

WINDOW_SAVE_DEBOUNCE_MS: int = 400
WINDOW_DEFAULT_SCREEN_RATIO: float = 0.8
WINDOW_MIN_VISIBLE_WIDTH: int = 240
WINDOW_MIN_VISIBLE_HEIGHT: int = 32
WINDOW_RECT_SEPARATOR: str = ","
WINDOW_RECT_FIELD_COUNT: int = 4

MONITOR_ORIENTATION_LANDSCAPE: str = "L"
MONITOR_ORIENTATION_PORTRAIT: str = "P"
MONITOR_NO_INDEX: int = -1

WIN_DWM_IMMERSIVE_DARK_MODE_ATTRIBUTE: int = 20

LOG_PREFIX_VOICE: str = "[Lloyd voice]"
LOG_PREFIX_AGENT: str = "[Lloyd agent]"
LOG_PREFIX_ERROR: str = "[Lloyd Error]"
LOG_PREFIX_RENDER: str = "[Lloyd render]"