ANIM_BACKEND_CANVAS: str = "canvas"
ANIM_BACKEND_MANIM: str = "manim"
ANIM_BACKEND_BOTH: str = "both"
ANIM_BACKEND: str = ANIM_BACKEND_CANVAS

ANIM_CANVAS_SCENE_WIDTH: float = 14.2
ANIM_CANVAS_SCENE_HEIGHT: float = 8.0
ANIM_CANVAS_FADE_MS: int = 320
ANIM_CANVAS_STEP_PAUSE_MS: int = 450
ANIM_CANVAS_HOLD_MS: int = 1200
ANIM_CANVAS_TITLE_PT: int = 18
ANIM_CANVAS_STEP_TITLE_PT: int = 13
ANIM_CANVAS_STEP_DESC_PT: int = 10
ANIM_CANVAS_LABEL_PT: int = 8
ANIM_CANVAS_LOOP_COUNT: int = -1
ANIM_VESSEL_LABEL_OPACITY: float = 0.85

ANIM_CANVAS_INGREDIENT_PT_NORMAL: int = 9
ANIM_CANVAS_INGREDIENT_PT_COMPACT: int = 8
ANIM_CANVAS_INGREDIENT_PANEL_X_INSET: float = 3.9
ANIM_CANVAS_INGREDIENT_PANEL_Y_INSET: float = 0.3
ANIM_CANVAS_INGREDIENT_ROW_SPACING_NORMAL: float = 0.46
ANIM_CANVAS_INGREDIENT_ROW_SPACING_COMPACT: float = 0.38
ANIM_CANVAS_INGREDIENT_DOT_RADIUS: float = 0.075
ANIM_CANVAS_INGREDIENT_DOT_Y_OFFSET: float = 0.16
ANIM_CANVAS_INGREDIENT_LABEL_X_OFFSET: float = 0.22
ANIM_CANVAS_INGREDIENT_LABEL_COLOR: str = "#B8B8B8"