ANIM_BACKEND_CANVAS: str = "canvas"
ANIM_BACKEND_MANIM: str = "manim"
ANIM_BACKEND_BOTH: str = "both"
ANIM_BACKEND: str = ANIM_BACKEND_CANVAS

ANIM_CANVAS_SCENE_WIDTH: float = 14.2
ANIM_CANVAS_SCENE_HEIGHT: float = 8.0
ANIM_CANVAS_FADE_MS: int = 320
ANIM_CANVAS_STEP_PAUSE_MS: int = 450
ANIM_CANVAS_HOLD_MS: int = 1200
ANIM_CANVAS_TITLE_PT: int = 18
ANIM_CANVAS_STEP_TITLE_PT: int = 13
ANIM_CANVAS_STEP_DESC_PT: int = 10
ANIM_CANVAS_LABEL_PT: int = 8
ANIM_CANVAS_LOOP_COUNT: int = -1
ANIM_VESSEL_LABEL_OPACITY: float = 0.85
