CHAT_PANEL_MIN_WIDTH: int = 320
CHAT_PANEL_MARGIN: int = 16
CHAT_PANEL_SPACING: int = 12
CHAT_HISTORY_SPACING: int = 8
CHAT_INPUT_ROW_SPACING: int = 8
CHAT_INPUT_PLACEHOLDER: str = "Message Lloyd..."
CHAT_SEND_BUTTON_TEXT: str = "Send"
CHAT_STOP_BUTTON_TEXT: str = "Stop"

CHAT_BUBBLE_MAX_WIDTH: int = 220
CHAT_BUBBLE_RADIUS: int = 14
CHAT_BUBBLE_PADDING: int = 10

CHAT_CLEAR_COMMAND_TEXT: str = "/clear"
CHAT_CLEAR_VOICE_PHRASES: tuple[str, ...] = (
    "clear the chat", "clean the chat", "clear chat", "clean chat",
)
CHAT_CLEAR_VOICE_MATCH_THRESHOLD: int = 85

TYPING_DOT_COUNT: int = 3
TYPING_DOT_RADIUS: float = 4.0
TYPING_DOT_SPACING: float = 16.0
TYPING_BOUNCE_HEIGHT: float = 5.0
TYPING_FRAME_INTERVAL_MS: int = 16
TYPING_CYCLE_SPEED: float = 4.5
TYPING_BUBBLE_WIDTH: int = 60
TYPING_BUBBLE_HEIGHT: int = 32
TYPING_DOT_PHASE_OFFSET: float = 0.9

MUTE_BUTTON_ICON_UNMUTED: str = "🔊"
MUTE_BUTTON_ICON_MUTED: str = "🔇"
MUTE_BUTTON_SIZE: int = 36
MUTE_BUTTON_RADIUS: int = 18
MUTE_BUTTON_MARGIN: int = 12

MIC_BUTTON_LISTENING_TEXT: str = "Mic: Listening"
MIC_BUTTON_MUTED_TEXT: str = "Mic: Muted"
MIC_BUTTON_LOADING_TEXT: str = "Speech model is loading"
