PANEL_BORDER_WIDTH: int = 2
PANEL_BORDER_RADIUS: int = 8
PANEL_BORDER_MARGIN: int = 8
PANEL_BODY_MARGIN: int = 6
PANEL_HEADER_HEIGHT: int = 22
PANEL_HEADER_SPACING: int = 4
PANEL_CLOSE_BUTTON_SIZE: int = 16
PANEL_CLOSE_BUTTON_RADIUS: int = 8
PANEL_CLOSE_GLYPH: str = "✕"
PANEL_TITLE_MAX_LENGTH: int = 30
PANEL_ACTION_BUTTON_HEIGHT: int = 16
PANEL_ACTION_BUTTON_RADIUS: int = 4
PANEL_ACTION_BUTTON_PADDING_H: int = 8

VIDEO_PREVIEW_DEFAULT_WIDTH: int = 420
VIDEO_PREVIEW_DEFAULT_HEIGHT: int = 260
VIDEO_PREVIEW_POSITION_OFFSET: int = 25

VIDEO_MIN_WIDTH: int = 260
VIDEO_MIN_HEIGHT: int = 160
VIDEO_DEFAULT_WIDTH: int = 380
VIDEO_DEFAULT_HEIGHT: int = 240
VIDEO_PLAYER_BORDER_RADIUS: int = 4
VIDEO_DEFAULT_TITLE: str = "ANIMATION PREVIEW"

CANVAS_POPUP_DEFAULT_WIDTH: int = 520
CANVAS_POPUP_DEFAULT_HEIGHT: int = 320
CANVAS_POPUP_MIN_WIDTH: int = 320
CANVAS_POPUP_MIN_HEIGHT: int = 200
CANVAS_POPUP_DEFAULT_TITLE: str = "COCKTAIL BUILD"
CANVAS_POPUP_EXPORT_TEXT: str = "MP4"
CANVAS_POPUP_EXPORTING_TEXT: str = "RENDERING..."

RECIPE_POPUP_DEFAULT_WIDTH: int = 380
RECIPE_POPUP_DEFAULT_HEIGHT: int = 420
RECIPE_POPUP_POSITION_OFFSET: int = 25
RECIPE_POPUP_BORDER_MARGIN: int = 8
RECIPE_POPUP_MIN_WIDTH: int = 280
RECIPE_POPUP_MIN_HEIGHT: int = 220
RECIPE_POPUP_HEADER_HEIGHT: int = 22
RECIPE_POPUP_BORDER_WIDTH: int = 2
RECIPE_POPUP_BORDER_RADIUS: int = 8
RECIPE_POPUP_CLOSE_BUTTON_SIZE: int = 16
RECIPE_POPUP_CLOSE_BUTTON_RADIUS: int = 8
RECIPE_POPUP_CLOSE_GLYPH: str = "✕"
RECIPE_POPUP_STEP_BADGE_SIZE: int = 22
RECIPE_POPUP_DEFAULT_TITLE: str = "RECIPE"
RECIPE_POPUP_TITLE_MAX_LENGTH: int = 30
