PHONE_SCAN_PORT: int = 8080
PHONE_SCAN_UPLOAD_DIR: str = "output"
PHONE_SCAN_HTML_FILENAME: str = "scan_phone.html"
PHONE_SCAN_POLL_INTERVAL_S: float = 0.1

PHONE_SCAN_WINDOW_TITLE: str = "Lloyd — Wi-Fi Mobile Transmitter Receiver"
PHONE_SCAN_WINDOW_WIDTH: int = 850
PHONE_SCAN_WINDOW_HEIGHT: int = 520

PHONE_SCAN_MAIN_MARGIN: int = 24
PHONE_SCAN_MAIN_SPACING: int = 20
PHONE_SCAN_PANEL_MARGIN: int = 20
PHONE_SCAN_PANEL_BORDER_RADIUS: int = 8

PHONE_SCAN_QR_BOX_SIZE: int = 6
PHONE_SCAN_QR_BORDER: int = 2
PHONE_SCAN_QR_FILL_COLOR: str = "black"
PHONE_SCAN_QR_BACK_COLOR: str = "white"

PHONE_SCAN_PANEL_BG: str = "#121824"
PHONE_SCAN_PANEL_BORDER: str = "#1f2d47"
PHONE_SCAN_SUBTEXT_COLOR: str = "#90A4AE"
PHONE_SCAN_URL_TEXT_COLOR: str = "#ECEFF1"
PHONE_SCAN_PREVIEW_PLACEHOLDER_COLOR: str = "#546E7A"

PHONE_SCAN_TITLE_FONT_SIZE: int = 16
PHONE_SCAN_INSTRUCTIONS_FONT_SIZE: int = 12
PHONE_SCAN_URL_FONT_SIZE: int = 13
PHONE_SCAN_STATUS_FONT_SIZE: int = 14
PHONE_SCAN_PREVIEW_FONT_SIZE: int = 14

PHONE_SCAN_TITLE_TEXT: str = "MOBILE BAR SCANNER"
PHONE_SCAN_INSTRUCTIONS_TEXT: str = "Scan with phone camera while on the same Wi-Fi:"
PHONE_SCAN_STATUS_WAITING_TEXT: str = "LATEST SCAN: WAITING FOR PHOTO"
PHONE_SCAN_PREVIEW_PLACEHOLDER_TEXT: str = "No snapshot received yet"
PHONE_SCAN_CANCELLED_MESSAGE: str = "Scan cancelled before a photo was received."
