MANIM_OUTPUT_DIR: str = "output"
MANIM_TEMP_DIR_PREFIX: str = "media_temp_"
MANIM_QUALITY: str = "low_quality"
MANIM_VERBOSITY: str = "ERROR"
MANIM_VIDEO_EXTENSION: str = ".mp4"
MANIM_RENDERER: str = "cairo"
MANIM_DISABLE_CACHING: bool = True
MANIM_PROGRESS_BAR: str = "none"

MANIM_RENDER_MODULE: str = "app.render.cli"
MANIM_RENDER_OK_MARKER: str = "RENDER_OK:"
MANIM_RENDER_FAILED_MARKER: str = "RENDER_FAILED:"
MANIM_SPEC_FILE_PREFIX: str = "lloyd_spec_"
MANIM_SPEC_SIDECAR_EXTENSION: str = ".json"

RENDER_KILL_TIMEOUT_MS: int = 3000
