from app.config.env import (
    ENV_EDGE_PITCH_KEY, ENV_EDGE_RATE_KEY, ENV_EDGE_VOICE_KEY,
    ENV_VOICE_KEY, ENV_VOICE_LENGTH_KEY, ENV_VOICE_NOISE_KEY,
    ENV_VOICE_NOISE_W_KEY, ENV_VOICE_SPEAKER_KEY, ENV_VOICE_VOLUME_KEY,
    env_float, env_int, env_value,
)

SPEECH_STRIP_MARKDOWN_PATTERN: str = r"[\*#_`~]"
SPEECH_STRIP_EMOJI_PATTERN: str = r"[\U00010000-\U0010ffff]"
SPEECH_FRACTION_REPLACEMENTS: dict[str, str] = {
    "1/2": "half",
    "1/4": "quarter",
    "3/4": "three quarters",
    "1/3": "one third",
    "2/3": "two thirds",
}
SPEECH_ML_PATTERN: str = r"(\d+(?:\.\d+)?)\s*ml\b"
SPEECH_ML_REPLACEMENT: str = r"\1 milliliters"
SPEECH_CL_PATTERN: str = r"(\d+(?:\.\d+)?)\s*cl\b"
SPEECH_CL_REPLACEMENT: str = r"\1 centiliters"
SPEECH_OZ_PATTERN: str = r"(\d+(?:\.\d+)?)\s*oz\b"
SPEECH_OZ_REPLACEMENT: str = r"\1 ounces"
SPEECH_NUMBER_RANGE_PATTERN: str = r"(\d+)\s*-\s*(\d+)"
SPEECH_NUMBER_RANGE_REPLACEMENT: str = r"\1 to \2"
SPEECH_CELSIUS_PATTERN: str = r"(\d+)\s*°\s*C"
SPEECH_CELSIUS_REPLACEMENT: str = r"\1 degrees Celsius"
SPEECH_SENTENCE_SPLIT_PATTERN: str = r"(?<=[.!?])\s+"

TTS_ENGINE_PIPER: str = "piper"
TTS_ENGINE_EDGE: str = "edge"

TTS_VOICES_DIR: str = "voices"
TTS_VOICE_MODEL_EXTENSION: str = ".onnx"
TTS_VOICE_CONFIG_SUFFIX: str = ".json"

TTS_VOICE_NEUTRAL_MULTIPLIER: float = 1.0
TTS_VOICE_DEFAULT_VOLUME: float = 1.0

TTS_VOICE_DEFAULT_ID: str = "alan"
TTS_VOICE_DEFAULT_MODEL: str = "en_GB-alan-medium"

TTS_VOICE_ID: str = env_value(ENV_VOICE_KEY, TTS_VOICE_DEFAULT_ID)
TTS_VOICE_LENGTH_MULTIPLIER: float = env_float(
    ENV_VOICE_LENGTH_KEY, TTS_VOICE_NEUTRAL_MULTIPLIER
)
TTS_VOICE_NOISE_MULTIPLIER: float = env_float(
    ENV_VOICE_NOISE_KEY, TTS_VOICE_NEUTRAL_MULTIPLIER
)
TTS_VOICE_NOISE_W_MULTIPLIER: float = env_float(
    ENV_VOICE_NOISE_W_KEY, TTS_VOICE_NEUTRAL_MULTIPLIER
)
TTS_VOICE_VOLUME: float = env_float(ENV_VOICE_VOLUME_KEY, TTS_VOICE_DEFAULT_VOLUME)
TTS_VOICE_SPEAKER: int | None = env_int(ENV_VOICE_SPEAKER_KEY)

TTS_EDGE_VOICE: str = env_value(ENV_EDGE_VOICE_KEY, "en-GB-RyanNeural")
TTS_EDGE_RATE: str = env_value(ENV_EDGE_RATE_KEY, "-4%")
TTS_EDGE_PITCH: str = env_value(ENV_EDGE_PITCH_KEY, "-2Hz")

TTS_PIPER_FALLBACK_SAMPLE_RATE: int = 22050
TTS_PIPER_DEFAULT_LENGTH_SCALE: float = 1.0
TTS_PIPER_DEFAULT_NOISE_SCALE: float = 0.667
TTS_PIPER_DEFAULT_NOISE_W: float = 0.8

TTS_WARMUP_TEXT: str = "Ready."
TTS_POLL_INTERVAL_MS: int = 50
TTS_INTER_SENTENCE_SILENCE_MS: int = 120
TTS_AUDIO_BLOCK_FRAMES: int = 512
TTS_AMPLITUDE_NORMALIZATION_PEAK: float = 6000.0