SPHERE_WIDGET_MIN_SIZE: int = 200

SPHERE_MAX_RADIUS: float = 160.0
SPHERE_BASE_RADIUS: float = 100.0
SPHERE_MIN_RENDER_RADIUS: float = 10.0
SPHERE_PULSE_AMPLITUDE: float = 18.0
SPHERE_PULSE_SPEED: float = 0.6
SPHERE_HUE_CYCLE_SPEED: float = 6.0
SPHERE_FRAME_INTERVAL_MS: int = 16
SPHERE_COLOR_START: str = "#3aa7ff"
SPHERE_GROW_SHRINK_DURATION_MS: int = 150
SPHERE_COLOR_TRANSITION_DURATION_MS: int = 500

SPHERE_IDLE_HUE_SATURATION: int = 160
SPHERE_IDLE_HUE_VALUE: int = 255
SPHERE_CORE_LIGHTEN: int = 140
SPHERE_EDGE_ALPHA: int = 20
SPHERE_GRADIENT_STOP_CORE: float = 0.0
SPHERE_GRADIENT_STOP_MID: float = 0.6
SPHERE_GRADIENT_STOP_EDGE: float = 1.0
SPHERE_ORBIT_HIGHLIGHT_LIGHTEN: int = 180

SPHERE_COLOR_LISTENING: str = "#2f8fff"
SPHERE_COLOR_THINKING: str = "#00ff2a"
SPHERE_COLOR_SPEAKING: str = "#ffffff"
SPHERE_COLOR_RENDERING: str = "#ff9100"

SPHERE_LISTENING_GROWTH: float = 30.0

SPHERE_THINKING_PULSE_SPEED_MULTIPLIER: float = 2.2
SPHERE_THINKING_PULSE_AMPLITUDE_MULTIPLIER: float = 0.5
SPHERE_THINKING_ORBIT_SPEED: float = 140.0
SPHERE_THINKING_ORBIT_RADIUS_RATIO: float = 1.0
SPHERE_THINKING_ORBIT_DOT_RADIUS: float = 6.0

SPHERE_SPEAKING_AMPLITUDE_GROWTH: float = 45.0
SPHERE_SPEAKING_IDLE_BREATH_AMPLITUDE: float = 4.0
SPHERE_SPEAKING_SMOOTHING_RISE: float = 0.45
SPHERE_SPEAKING_SMOOTHING_FALL: float = 0.20
