COLOR_BG: str = "#0f0f10"
COLOR_CANVAS_BG: str = "#121214"
COLOR_PANEL_BG: str = "#18181b"
COLOR_BORDER: str = "#2b2b2e"
COLOR_TEXT_PRIMARY: str = "#f3f3f3"
COLOR_TEXT_SECONDARY: str = "#a0a0a6"
COLOR_ACCENT: str = "#60cdff"
COLOR_INPUT_BG: str = "#1f1f22"

COLOR_BUBBLE_USER_BG: str = "#2f6fed"
COLOR_BUBBLE_AGENT_BG: str = "#232326"
COLOR_BUBBLE_TEXT: str = "#f3f3f3"

COLOR_MIC_ACTIVE: str = "#ff5c5c"
COLOR_STOP_ACTIVE: str = "#ff5c5c"

COLOR_VIDEO_BG: str = "#0b0f19"
COLOR_VIDEO_TITLE: str = "#00E5FF"
COLOR_VIDEO_PLAYER_BG: str = "#000000"
COLOR_CLOSE_BUTTON_TEXT: str = "#FFFFFF"
COLOR_CLOSE_BUTTON_BG: str = "#C62828"
COLOR_CLOSE_BUTTON_HOVER_BG: str = "#E53935"

COLOR_PANEL_ACTION_BG: str = "#2b2b2e"
COLOR_PANEL_ACTION_HOVER_BG: str = "#3b3b40"
COLOR_PANEL_ACTION_TEXT: str = "#f3f3f3"
COLOR_PANEL_ACTION_DISABLED_TEXT: str = "#6e6e74"

COLOR_SCROLLBAR_TRACK: str = "#1f1f22"
COLOR_SCROLLBAR_HANDLE: str = "#6e6e74"
COLOR_SCROLLBAR_HANDLE_HOVER: str = "#84848a"
SCROLLBAR_WIDTH: int = 10
SCROLLBAR_HANDLE_MIN_HEIGHT: int = 32
SCROLLBAR_HANDLE_RADIUS: int = 5

FONT_FAMILY: str = "Segoe UI Variable, Segoe UI"
FONT_SIZE_NORMAL: int = 10
FONT_SIZE_VIDEO_TITLE: int = 11
FONT_SIZE_CLOSE_BUTTON: int = 9

STYLE_BORDER_WIDTH: int = 1
STYLE_INPUT_BORDER_RADIUS: int = 6
STYLE_INPUT_PADDING: int = 8
STYLE_BUTTON_BORDER_RADIUS: int = 6
STYLE_BUTTON_PADDING_V: int = 8
STYLE_BUTTON_PADDING_H: int = 14

OBJECT_NAME_CANVAS_PANEL: str = "canvasPanel"
OBJECT_NAME_CHAT_PANEL: str = "chatPanel"
OBJECT_NAME_CHAT_HISTORY: str = "chatHistory"
OBJECT_NAME_USER_BUBBLE: str = "userBubble"
OBJECT_NAME_AGENT_BUBBLE: str = "agentBubble"
OBJECT_NAME_MIC_TOGGLE_BUTTON: str = "micToggleButton"
OBJECT_NAME_MUTE_BUTTON: str = "muteButton"
OBJECT_NAME_SEND_BUTTON: str = "sendButton"
OBJECT_NAME_VIDEO_WIDGET: str = "TopLeftVideoWidget"
OBJECT_NAME_CANVAS_POPUP: str = "cocktailCanvasPopup"
