# UI

ORG_NAME: str = "Lloyd"
APP_NAME: str = "Lloyd"

WINDOW_TITLE: str = "Lloyd"
WINDOW_MIN_WIDTH: int = 1024
WINDOW_MIN_HEIGHT: int = 640

CHAT_PANEL_MIN_WIDTH: int = 320
SPLITTER_HANDLE_WIDTH: int = 4
SPLITTER_STRETCH_CANVAS: int = 3
SPLITTER_STRETCH_CHAT: int = 1
SPLITTER_DEFAULT_CANVAS_RATIO: float = 0.75
SPLITTER_DEFAULT_CHAT_RATIO: float = 0.25

FULLSCREEN_SHORTCUT_F11: str = "F11"
FULLSCREEN_SHORTCUT_ESC: str = "Esc"

SETTINGS_GEOMETRY_KEY: str = "window/geometry"
SETTINGS_SPLITTER_STATE_KEY: str = "window/splitter_state"

VIDEO_PREVIEW_DEFAULT_WIDTH: int = 420
VIDEO_PREVIEW_DEFAULT_HEIGHT: int = 260
VIDEO_PREVIEW_POSITION_OFFSET: int = 25

# WINDOWS INTEGRATION

WIN_DWM_IMMERSIVE_DARK_MODE_ATTRIBUTE: int = 20

# COLORS

COLOR_BG: str = "#0f0f10"
COLOR_CANVAS_BG: str = "#121214"
COLOR_PANEL_BG: str = "#18181b"
COLOR_BORDER: str = "#2b2b2e"
COLOR_TEXT_PRIMARY: str = "#f3f3f3"
COLOR_TEXT_SECONDARY: str = "#a0a0a6"
COLOR_ACCENT: str = "#60cdff"
COLOR_INPUT_BG: str = "#1f1f22"

COLOR_BUBBLE_USER_BG: str = "#2f6fed"
COLOR_BUBBLE_AGENT_BG: str = "#232326"
COLOR_BUBBLE_TEXT: str = "#f3f3f3"

COLOR_MIC_ACTIVE: str = "#ff5c5c"

COLOR_VIDEO_BORDER: str = "#00E5FF"
COLOR_VIDEO_BG: str = "#0b0f19"
COLOR_VIDEO_TITLE: str = "#00E5FF"
COLOR_VIDEO_PLAYER_BG: str = "#000000"
COLOR_CLOSE_BUTTON_TEXT: str = "#FFFFFF"
COLOR_CLOSE_BUTTON_BG: str = "#C62828"
COLOR_CLOSE_BUTTON_HOVER_BG: str = "#E53935"

# FONTS

FONT_FAMILY: str = "Segoe UI Variable, Segoe UI"
FONT_SIZE_NORMAL: int = 10
FONT_SIZE_SMALL: int = 9
FONT_SIZE_VIDEO_TITLE: int = 11
FONT_SIZE_CLOSE_BUTTON: int = 9

# THEME

STYLE_BORDER_WIDTH: int = 1
STYLE_INPUT_BORDER_RADIUS: int = 6
STYLE_INPUT_PADDING: int = 8
STYLE_BUTTON_BORDER_RADIUS: int = 6
STYLE_BUTTON_PADDING_V: int = 8
STYLE_BUTTON_PADDING_H: int = 14

# CHAT

CHAT_BUBBLE_MAX_WIDTH: int = 220
CHAT_BUBBLE_RADIUS: int = 14
CHAT_BUBBLE_PADDING: int = 10

CHAT_PANEL_MARGIN: int = 16
CHAT_PANEL_SPACING: int = 12
CHAT_HISTORY_SPACING: int = 8
CHAT_INPUT_ROW_SPACING: int = 8
CHAT_INPUT_PLACEHOLDER: str = "Message Lloyd..."
CHAT_SEND_BUTTON_TEXT: str = "Send"

# TYPING INDICATOR

TYPING_DOT_COUNT: int = 3
TYPING_DOT_RADIUS: float = 4.0
TYPING_DOT_SPACING: float = 16.0
TYPING_BOUNCE_HEIGHT: float = 5.0
TYPING_FRAME_INTERVAL_MS: int = 16
TYPING_CYCLE_SPEED: float = 4.5
TYPING_BUBBLE_WIDTH: int = 60
TYPING_BUBBLE_HEIGHT: int = 32
TYPING_DOT_PHASE_OFFSET: float = 0.9

# SPHERE

SPHERE_WIDGET_MIN_SIZE: int = 200

SPHERE_MIN_RADIUS: float = 60.0
SPHERE_MAX_RADIUS: float = 160.0
SPHERE_BASE_RADIUS: float = 100.0
SPHERE_MIN_RENDER_RADIUS: float = 10.0
SPHERE_PULSE_AMPLITUDE: float = 18.0
SPHERE_PULSE_SPEED: float = 0.6
SPHERE_HUE_CYCLE_SPEED: float = 6.0
SPHERE_FRAME_INTERVAL_MS: int = 16
SPHERE_COLOR_START: str = "#3aa7ff"
SPHERE_GROW_SHRINK_DURATION_MS: int = 400
SPHERE_COLOR_TRANSITION_DURATION_MS: int = 500

SPHERE_IDLE_HUE_SATURATION: int = 160
SPHERE_IDLE_HUE_VALUE: int = 255
SPHERE_CORE_LIGHTEN: int = 140
SPHERE_EDGE_ALPHA: int = 20
SPHERE_GRADIENT_STOP_CORE: float = 0.0
SPHERE_GRADIENT_STOP_MID: float = 0.6
SPHERE_GRADIENT_STOP_EDGE: float = 1.0
SPHERE_ORBIT_HIGHLIGHT_LIGHTEN: int = 180

SPHERE_COLOR_LISTENING: str = "#2f8fff"
SPHERE_COLOR_THINKING: str = "#00ff2a"
SPHERE_COLOR_SPEAKING: str = "#ffffff"

SPHERE_LISTENING_GROWTH: float = 30.0

SPHERE_THINKING_PULSE_SPEED_MULTIPLIER: float = 2.2
SPHERE_THINKING_PULSE_AMPLITUDE_MULTIPLIER: float = 0.5
SPHERE_THINKING_ORBIT_SPEED: float = 140.0
SPHERE_THINKING_ORBIT_RADIUS_RATIO: float = 1.0
SPHERE_THINKING_ORBIT_DOT_RADIUS: float = 6.0

SPHERE_SPEAKING_MIN_JITTER: float = 10.0
SPHERE_SPEAKING_MAX_JITTER: float = 35.0
SPHERE_SPEAKING_JITTER_DURATION_MS: int = 120
SPHERE_SPEAKING_JITTER_MIN_INTERVAL_S: float = 0.08
SPHERE_SPEAKING_JITTER_MAX_INTERVAL_S: float = 0.22

# VIDEO PREVIEW

VIDEO_BORDER_MARGIN: int = 8
VIDEO_MIN_WIDTH: int = 260
VIDEO_MIN_HEIGHT: int = 160
VIDEO_DEFAULT_WIDTH: int = 380
VIDEO_DEFAULT_HEIGHT: int = 240
VIDEO_HEADER_HEIGHT: int = 22
VIDEO_CLOSE_BUTTON_SIZE: int = 16
VIDEO_BORDER_WIDTH: int = 2
VIDEO_BORDER_RADIUS: int = 8
VIDEO_PLAYER_BORDER_RADIUS: int = 4
VIDEO_CLOSE_BUTTON_RADIUS: int = 8
VIDEO_DEFAULT_TITLE: str = "ANIMATION PREVIEW"
VIDEO_TITLE_MAX_LENGTH: int = 30
VIDEO_CLOSE_GLYPH: str = "✕"

# MIC BUTTON

MIC_BUTTON_LISTENING_TEXT: str = "Mic: Listening"
MIC_BUTTON_MUTED_TEXT: str = "Mic: Muted"

# OBJECT NAMES

OBJECT_NAME_CANVAS_PANEL: str = "canvasPanel"
OBJECT_NAME_CHAT_PANEL: str = "chatPanel"
OBJECT_NAME_CHAT_HISTORY: str = "chatHistory"
OBJECT_NAME_USER_BUBBLE: str = "userBubble"
OBJECT_NAME_AGENT_BUBBLE: str = "agentBubble"
OBJECT_NAME_MIC_TOGGLE_BUTTON: str = "micToggleButton"
OBJECT_NAME_VIDEO_WIDGET: str = "TopLeftVideoWidget"

# LOGGING

LOG_PREFIX_VOICE: str = "[Lloyd voice]"
LOG_PREFIX_AGENT: str = "[Lloyd agent]"
LOG_PREFIX_ERROR: str = "[Lloyd Error]"

# VOICE INPUT

VOICE_WAKE_WORDS = ("lloyd", "hey lloyd")
VOICE_RECOGNITION_LANGUAGE: str = "en-US"

# SPEECH TEXT CLEANING

SPEECH_STRIP_MARKDOWN_PATTERN: str = r"[\*#_`~]"
SPEECH_STRIP_EMOJI_PATTERN: str = r"[\U00010000-\U0010ffff]"
SPEECH_FRACTION_REPLACEMENTS: dict[str, str] = {
    "1/2": "half",
    "1/4": "quarter",
    "3/4": "three quarters",
    "1/3": "one third",
    "2/3": "two thirds",
}
SPEECH_ML_PATTERN: str = r"(\d+(?:\.\d+)?)\s*ml\b"
SPEECH_ML_REPLACEMENT: str = r"\1 milliliters"
SPEECH_CL_PATTERN: str = r"(\d+(?:\.\d+)?)\s*cl\b"
SPEECH_CL_REPLACEMENT: str = r"\1 centiliters"
SPEECH_OZ_PATTERN: str = r"(\d+(?:\.\d+)?)\s*oz\b"
SPEECH_OZ_REPLACEMENT: str = r"\1 ounces"
SPEECH_NUMBER_RANGE_PATTERN: str = r"(\d+)\s*-\s*(\d+)"
SPEECH_NUMBER_RANGE_REPLACEMENT: str = r"\1 to \2"
SPEECH_CELSIUS_PATTERN: str = r"(\d+)\s*°\s*C"
SPEECH_CELSIUS_REPLACEMENT: str = r"\1 degrees Celsius"

# TTS

TTS_VOICE: str = "en-GB-RyanNeural"
TTS_POLL_INTERVAL_MS: int = 50

# MANIM RENDER

MANIM_OUTPUT_DIR: str = "output"
MANIM_TEMP_DIR_PREFIX: str = "media_temp_"
MANIM_QUALITY: str = "low_quality"
MANIM_VERBOSITY: str = "ERROR"
MANIM_VIDEO_EXTENSION: str = ".mp4"

# COCKTAIL ANIMATION

ANIM_GLASS_STROKE_WIDTH: float = 3.5
ANIM_ACCENT_STROKE_WIDTH: float = 4.5
ANIM_STRAIN_ARC_STROKE_WIDTH: float = 5.5

ANIM_TITLE_FONT_SIZE: int = 34
ANIM_TITLE_BUFF: float = 0.35
ANIM_INGREDIENT_FONT_SIZE: int = 16
ANIM_INGREDIENT_DOT_RADIUS: float = 0.09
ANIM_INGREDIENT_ROW_BUFF: float = 0.18
ANIM_INGREDIENT_PANEL_BUFF: float = 0.55
ANIM_INGREDIENT_FADE_LAG_RATIO: float = 0.08

ANIM_STEP_TITLE_FONT_SIZE: int = 28
ANIM_STEP_DESC_FONT_SIZE: int = 19
ANIM_STEP_DESC_LINE_SPACING: float = 1.2
ANIM_STEP_DESC_MAX_HEIGHT: float = 2.0
ANIM_STEP_TEXT_WRAP_WIDTH: int = 38
ANIM_INFO_BOX_BUFF: float = 0.45
ANIM_INFO_BOX_ROW_BUFF: float = 0.18

ANIM_DEFAULT_STEP_WAIT_S: float = 0.4
ANIM_FINAL_WAIT_S: float = 1.5

ANIM_COLOR_HERB_DEFAULT: str = "#2E7D32"
ANIM_COLOR_CAMPARI: str = "#C41E3A"
ANIM_COLOR_BOURBON: str = "#C86D27"
ANIM_COLOR_DEFAULT_LIQUID: str = "#E0A96D"
ANIM_COLOR_SUGAR_CUBE: str = "#F8F9FA"
ANIM_COLOR_MUDDLE_PASTE: str = "#5A1608"
ANIM_COLOR_BITTERS_DEFAULT: str = "#4A1208"
ANIM_COLOR_ORANGE_TWIST: str = "#FF8C00"
ANIM_COLOR_MINT_LEAF_1: str = "#3B7A57"
ANIM_COLOR_MINT_LEAF_2: str = "#2E7D32"
ANIM_COLOR_MINT_LEAF_3: str = "#43A047"
ANIM_COLOR_GARNISH_LEAF_1: str = "#3B7A57"
ANIM_COLOR_GARNISH_LEAF_2: str = "#4E9B6E"

ANIM_SUGAR_CUBE_SIDE: float = 0.38
ANIM_SUGAR_CUBE_STROKE_WIDTH: float = 2
ANIM_ICE_MEDIUM_SIDE: float = 0.42
ANIM_ICE_LARGE_SIDE: float = 0.55
ANIM_ICE_SMALL_SIDE: float = 0.28
ANIM_ICE_FILL_OPACITY_MEDIUM: float = 0.55
ANIM_ICE_FILL_OPACITY_LARGE: float = 0.6
ANIM_ICE_FILL_OPACITY_SMALL: float = 0.7
ANIM_ICE_STROKE_WIDTH_THIN: float = 1
ANIM_ICE_STROKE_WIDTH_MEDIUM: float = 1.5

ANIM_MUDDLER_CORNER_RADIUS: float = 0.06
ANIM_MUDDLER_HEIGHT: float = 2.4
ANIM_MUDDLER_WIDTH: float = 0.28

ANIM_SHAKER_CORNER_RADIUS: float = 0.15
ANIM_SHAKER_HEIGHT: float = 3.6
ANIM_SHAKER_WIDTH: float = 1.8

ANIM_BARSPOON_ORBIT_X: float = 0.24

ANIM_LAYER_FILL_OPACITY: float = 0.9
ANIM_SHAKEN_FILL_OPACITY: float = 0.95
ANIM_STIRRED_FILL_OPACITY: float = 0.92
ANIM_STRAINED_FILL_OPACITY: float = 0.88