# UI
ORG_NAME: str = "Lloyd"
APP_NAME: str = "Lloyd"

WINDOW_TITLE: str = "Lloyd"
WINDOW_MIN_WIDTH: int = 1024
WINDOW_MIN_HEIGHT: int = 640

CHAT_PANEL_MIN_WIDTH: int = 320
SPLITTER_HANDLE_WIDTH: int = 4
SPLITTER_STRETCH_CANVAS: int = 3
SPLITTER_STRETCH_CHAT: int = 1
SPLITTER_DEFAULT_CANVAS_RATIO: float = 0.75
SPLITTER_DEFAULT_CHAT_RATIO: float = 0.25

FULLSCREEN_SHORTCUT_F11: str = "F11"
FULLSCREEN_SHORTCUT_ESC: str = "Esc"

SETTINGS_GEOMETRY_KEY: str = "window/geometry"
SETTINGS_SPLITTER_STATE_KEY: str = "window/splitter_state"

VIDEO_PREVIEW_DEFAULT_WIDTH: int = 420
VIDEO_PREVIEW_DEFAULT_HEIGHT: int = 260
VIDEO_PREVIEW_POSITION_OFFSET: int = 25

# WINDOWS INTEGRATION
WIN_DWM_IMMERSIVE_DARK_MODE_ATTRIBUTE: int = 20

# COLORS
COLOR_BG: str = "#0f0f10"
COLOR_CANVAS_BG: str = "#121214"
COLOR_PANEL_BG: str = "#18181b"
COLOR_BORDER: str = "#2b2b2e"
COLOR_TEXT_PRIMARY: str = "#f3f3f3"
COLOR_TEXT_SECONDARY: str = "#a0a0a6"
COLOR_ACCENT: str = "#60cdff"
COLOR_INPUT_BG: str = "#1f1f22"

COLOR_BUBBLE_USER_BG: str = "#2f6fed"
COLOR_BUBBLE_AGENT_BG: str = "#232326"
COLOR_BUBBLE_TEXT: str = "#f3f3f3"

COLOR_MIC_ACTIVE: str = "#ff5c5c"

COLOR_VIDEO_BORDER: str = "#00E5FF"
COLOR_VIDEO_BG: str = "#0b0f19"
COLOR_VIDEO_TITLE: str = "#00E5FF"
COLOR_VIDEO_PLAYER_BG: str = "#000000"
COLOR_CLOSE_BUTTON_TEXT: str = "#FFFFFF"
COLOR_CLOSE_BUTTON_BG: str = "#C62828"
COLOR_CLOSE_BUTTON_HOVER_BG: str = "#E53935"

COLOR_RECIPE_BG: str = "#1a1a24"
COLOR_RECIPE_BORDER: str = "#00E5FF"
COLOR_RECIPE_TITLE: str = "#ffffff"
COLOR_RECIPE_CLOSE_TEXT: str = "#ffffff"
COLOR_RECIPE_CLOSE_BG: str = "#28283a"
COLOR_RECIPE_CLOSE_HOVER_BG: str = "#e63946"
COLOR_RECIPE_BADGE_BG: str = "#262638"
COLOR_RECIPE_INGREDIENTS_BG: str = "#212130"
COLOR_RECIPE_INGREDIENT_NAME: str = "#dcdce6"
COLOR_RECIPE_INGREDIENT_VALUE: str = "#e0a96d"
COLOR_RECIPE_STEP_BADGE_BG: str = "#3b3b54"
COLOR_RECIPE_STEP_TEXT: str = "#cccccc"
COLOR_RECIPE_GARNISH_TEXT: str = "#9a9ab0"

# FONTS
FONT_FAMILY: str = "Segoe UI Variable, Segoe UI"
FONT_SIZE_NORMAL: int = 10
FONT_SIZE_SMALL: int = 9
FONT_SIZE_VIDEO_TITLE: int = 11
FONT_SIZE_CLOSE_BUTTON: int = 9

FONT_SIZE_RECIPE_TITLE: int = 22
FONT_SIZE_RECIPE_CLOSE_BUTTON: int = 9
FONT_SIZE_RECIPE_BADGE: int = 10
FONT_SIZE_RECIPE_INGREDIENT: int = 12
FONT_SIZE_RECIPE_STEP: int = 12
FONT_SIZE_RECIPE_STEP_BADGE: int = 11
FONT_SIZE_RECIPE_GARNISH: int = 11

# THEME
STYLE_BORDER_WIDTH: int = 1
STYLE_INPUT_BORDER_RADIUS: int = 6
STYLE_INPUT_PADDING: int = 8
STYLE_BUTTON_BORDER_RADIUS: int = 6
STYLE_BUTTON_PADDING_V: int = 8
STYLE_BUTTON_PADDING_H: int = 14

# CHAT
CHAT_BUBBLE_MAX_WIDTH: int = 220
CHAT_BUBBLE_RADIUS: int = 14
CHAT_BUBBLE_PADDING: int = 10

CHAT_PANEL_MARGIN: int = 16
CHAT_PANEL_SPACING: int = 12
CHAT_HISTORY_SPACING: int = 8
CHAT_INPUT_ROW_SPACING: int = 8
CHAT_INPUT_PLACEHOLDER: str = "Message Lloyd..."
CHAT_SEND_BUTTON_TEXT: str = "Send"

CHAT_STOP_BUTTON_TEXT: str = "Stop"
OBJECT_NAME_SEND_BUTTON: str = "sendButton"
COLOR_STOP_ACTIVE: str = "#ff5c5c"

CHAT_CLEAR_COMMAND_TEXT: str = "/clear"
CHAT_CLEAR_VOICE_PHRASE: str = "clean the chat"
CHAT_CLEAR_VOICE_MATCH_THRESHOLD: int = 85

# SCROLLBAR
COLOR_SCROLLBAR_TRACK: str = "#1f1f22"
COLOR_SCROLLBAR_HANDLE: str = "#6e6e74"
COLOR_SCROLLBAR_HANDLE_HOVER: str = "#84848a"
SCROLLBAR_WIDTH: int = 10
SCROLLBAR_HANDLE_MIN_HEIGHT: int = 32
SCROLLBAR_HANDLE_RADIUS: int = 5

# MUTE BUTTON
OBJECT_NAME_MUTE_BUTTON: str = "muteButton"
MUTE_BUTTON_ICON_UNMUTED: str = "🔊"
MUTE_BUTTON_ICON_MUTED: str = "🔇"
MUTE_BUTTON_SIZE: int = 36
MUTE_BUTTON_RADIUS: int = 18
MUTE_BUTTON_MARGIN: int = 12

# TYPING INDICATOR
TYPING_DOT_COUNT: int = 3
TYPING_DOT_RADIUS: float = 4.0
TYPING_DOT_SPACING: float = 16.0
TYPING_BOUNCE_HEIGHT: float = 5.0
TYPING_FRAME_INTERVAL_MS: int = 16
TYPING_CYCLE_SPEED: float = 4.5
TYPING_BUBBLE_WIDTH: int = 60
TYPING_BUBBLE_HEIGHT: int = 32
TYPING_DOT_PHASE_OFFSET: float = 0.9

# SPHERE
SPHERE_WIDGET_MIN_SIZE: int = 200

SPHERE_MIN_RADIUS: float = 60.0
SPHERE_MAX_RADIUS: float = 160.0
SPHERE_BASE_RADIUS: float = 100.0
SPHERE_MIN_RENDER_RADIUS: float = 10.0
SPHERE_PULSE_AMPLITUDE: float = 18.0
SPHERE_PULSE_SPEED: float = 0.6
SPHERE_HUE_CYCLE_SPEED: float = 6.0
SPHERE_FRAME_INTERVAL_MS: int = 16
SPHERE_COLOR_START: str = "#3aa7ff"
SPHERE_GROW_SHRINK_DURATION_MS: int = 150
SPHERE_COLOR_TRANSITION_DURATION_MS: int = 500

SPHERE_IDLE_HUE_SATURATION: int = 160
SPHERE_IDLE_HUE_VALUE: int = 255
SPHERE_CORE_LIGHTEN: int = 140
SPHERE_EDGE_ALPHA: int = 20
SPHERE_GRADIENT_STOP_CORE: float = 0.0
SPHERE_GRADIENT_STOP_MID: float = 0.6
SPHERE_GRADIENT_STOP_EDGE: float = 1.0
SPHERE_ORBIT_HIGHLIGHT_LIGHTEN: int = 180

SPHERE_COLOR_LISTENING: str = "#2f8fff"
SPHERE_COLOR_THINKING: str = "#00ff2a"
SPHERE_COLOR_SPEAKING: str = "#ffffff"
SPHERE_COLOR_RENDERING: str = "#ff9100"

SPHERE_LISTENING_GROWTH: float = 30.0

SPHERE_THINKING_PULSE_SPEED_MULTIPLIER: float = 2.2
SPHERE_THINKING_PULSE_AMPLITUDE_MULTIPLIER: float = 0.5
SPHERE_THINKING_ORBIT_SPEED: float = 140.0
SPHERE_THINKING_ORBIT_RADIUS_RATIO: float = 1.0
SPHERE_THINKING_ORBIT_DOT_RADIUS: float = 6.0

SPHERE_SPEAKING_AMPLITUDE_GROWTH: float = 45.0
SPHERE_SPEAKING_IDLE_BREATH_AMPLITUDE: float = 4.0
SPHERE_SPEAKING_SMOOTHING_RISE: float = 0.45
SPHERE_SPEAKING_SMOOTHING_FALL: float = 0.20

# VIDEO PREVIEW
VIDEO_BORDER_MARGIN: int = 8
VIDEO_MIN_WIDTH: int = 260
VIDEO_MIN_HEIGHT: int = 160
VIDEO_DEFAULT_WIDTH: int = 380
VIDEO_DEFAULT_HEIGHT: int = 240
VIDEO_HEADER_HEIGHT: int = 22
VIDEO_CLOSE_BUTTON_SIZE: int = 16
VIDEO_BORDER_WIDTH: int = 2
VIDEO_BORDER_RADIUS: int = 8
VIDEO_PLAYER_BORDER_RADIUS: int = 4
VIDEO_CLOSE_BUTTON_RADIUS: int = 8
VIDEO_DEFAULT_TITLE: str = "ANIMATION PREVIEW"
VIDEO_TITLE_MAX_LENGTH: int = 30
VIDEO_CLOSE_GLYPH: str = "✕"

# RECIPE POPUP
RECIPE_POPUP_DEFAULT_WIDTH: int = 380
RECIPE_POPUP_DEFAULT_HEIGHT: int = 420
RECIPE_POPUP_POSITION_OFFSET: int = 25
RECIPE_POPUP_BORDER_MARGIN: int = 8
RECIPE_POPUP_MIN_WIDTH: int = 280
RECIPE_POPUP_MIN_HEIGHT: int = 220
RECIPE_POPUP_HEADER_HEIGHT: int = 22
RECIPE_POPUP_BORDER_WIDTH: int = 2
RECIPE_POPUP_BORDER_RADIUS: int = 8
RECIPE_POPUP_CLOSE_BUTTON_SIZE: int = 16
RECIPE_POPUP_CLOSE_BUTTON_RADIUS: int = 8
RECIPE_POPUP_CLOSE_GLYPH: str = "✕"
RECIPE_POPUP_STEP_BADGE_SIZE: int = 22
RECIPE_POPUP_DEFAULT_TITLE: str = "RECIPE"
RECIPE_POPUP_TITLE_MAX_LENGTH: int = 30

# MIC BUTTON
MIC_BUTTON_LISTENING_TEXT: str = "Mic: Listening"
MIC_BUTTON_MUTED_TEXT: str = "Mic: Muted"
MIC_BUTTON_LOADING_TEXT: str = "Speech model is loading"
MIC_BUTTON_LISTENING_TEXT: str = "Mic: Listening"
MIC_BUTTON_MUTED_TEXT: str = "Mic: Muted"

# OBJECT NAMES
OBJECT_NAME_CANVAS_PANEL: str = "canvasPanel"
OBJECT_NAME_CHAT_PANEL: str = "chatPanel"
OBJECT_NAME_CHAT_HISTORY: str = "chatHistory"
OBJECT_NAME_USER_BUBBLE: str = "userBubble"
OBJECT_NAME_AGENT_BUBBLE: str = "agentBubble"
OBJECT_NAME_MIC_TOGGLE_BUTTON: str = "micToggleButton"
OBJECT_NAME_VIDEO_WIDGET: str = "TopLeftVideoWidget"
OBJECT_NAME_RECIPE_WIDGET: str = "TopRightRecipyWidget"

# LOGGING
LOG_PREFIX_VOICE: str = "[Lloyd voice]"
LOG_PREFIX_AGENT: str = "[Lloyd agent]"
LOG_PREFIX_ERROR: str = "[Lloyd Error]"

# VOICE INPUT
VOICE_WAKE_KEYWORD: str = "lloyd"
VOICE_WAKE_KEYWORD_VARIANTS: tuple[str, ...] = ("lloyd", "loyd", "floyd", "boyd")
VOICE_WAKE_GREETINGS: tuple[str, ...] = ("hey", "hay", "hi", "ay")
VOICE_WAKE_KEYWORD_MATCH_THRESHOLD: int = 88
VOICE_WAKE_GREETING_MATCH_THRESHOLD: int = 80
VOICE_WAKE_KEYWORD_MAX_WORDS: int = 2
VOICE_WAKE_REFRACTORY_S: float = 1.5

VOICE_STOP_PHRASE: str = "lloyd stop"
VOICE_STOP_KEYWORD: str = "stop"
VOICE_STOP_KEYWORD_MATCH_THRESHOLD: int = 88

VOICE_WAKE_GRAMMAR_ENABLED: bool = False
VOICE_WAKE_GRAMMAR_UNKNOWN_TOKEN: str = "[unk]"

VOICE_VOSK_WAKE_MODEL_DIR: str = "models/vosk-model-small-en-us-0.15"
VOICE_RECOGNITION_LANGUAGE: str = "en-US"
VOICE_COMMAND_MODEL_WARMUP_SECONDS: float = 1.0

VOICE_WHISPER_MODEL_SIZE: str = "distil-small.en"
VOICE_WHISPER_DEVICE: str = "cpu"
VOICE_WHISPER_COMPUTE_TYPE: str = "int8"
VOICE_WHISPER_DOWNLOAD_ROOT: str = "models/whisper"
VOICE_WHISPER_LANGUAGE: str = "en"
VOICE_WHISPER_CPU_THREADS: int = 8

VOICE_WHISPER_BEAM_SIZE: int = 1
VOICE_WHISPER_BEST_OF: int = 1
VOICE_WHISPER_TEMPERATURE: float = 0.0
VOICE_WHISPER_CONDITION_ON_PREVIOUS_TEXT: bool = False
VOICE_WHISPER_WITHOUT_TIMESTAMPS: bool = True
VOICE_WHISPER_VAD_FILTER: bool = True

VOICE_SAMPLE_RATE_HZ: int = 16000
VOICE_AUDIO_DTYPE: str = "int16"
VOICE_BLOCK_SIZE_FRAMES: int = 2048

VOICE_AUDIO_QUEUE_MAX_S: float = 1.0
VOICE_PREROLL_S: float = 1.5
VOICE_PREROLL_SPEECH_PROBE_S: float = 0.25
VOICE_PAUSED_POLL_INTERVAL_MS: int = 250
VOICE_QUEUE_POLL_TIMEOUT_S: float = 0.2

VOICE_COMMAND_START_TIMEOUT_S: float = 5.0
VOICE_COMMAND_SILENCE_TIMEOUT_S: float = 0.4
VOICE_COMMAND_SILENCE_TIMEOUT_FALLBACK_S: float = 1.2
VOICE_COMMAND_MAX_DURATION_S: float = 12.0
VOICE_SILENCE_RMS_THRESHOLD: float = 300.0

VOICE_VAD_ENABLED: bool = True
VOICE_VAD_FRAME_SAMPLES: int = 512
VOICE_VAD_CONTEXT_SAMPLES: int = 64
VOICE_VAD_STATE_SIZE: int = 128
VOICE_VAD_SPEECH_THRESHOLD: float = 0.5
VOICE_VAD_SILENCE_THRESHOLD: float = 0.35

VOICE_STREAM_TRANSCRIPT_ENABLED: bool = True

VOICE_LOG_WAKE_MATCH: str = "Wake matched:"
VOICE_LOG_TRANSCRIPT_COMPARISON: str = "Transcript comparison:"

VOICE_MSG_NO_COMMAND_HEARD: str = "Didn't catch that — try again?"
VOICE_MSG_MODEL_MISSING: str = (
    "Voice input is unavailable: a Vosk model was not found. Download it "
    "and place it in the configured model directory."
)
VOICE_MSG_WAKE_GRAMMAR_UNSUPPORTED: str = (
    "Wake grammar rejected by the Vosk model; falling back to open recognition."
)
VOICE_MSG_VAD_UNAVAILABLE: str = (
    "Silero VAD unavailable; endpointing falls back to the RMS gate."
)

# SPEECH TEXT CLEANING
SPEECH_STRIP_MARKDOWN_PATTERN: str = r"[\*#_`~]"
SPEECH_STRIP_EMOJI_PATTERN: str = r"[\U00010000-\U0010ffff]"
SPEECH_FRACTION_REPLACEMENTS: dict[str, str] = {
    "1/2": "half",
    "1/4": "quarter",
    "3/4": "three quarters",
    "1/3": "one third",
    "2/3": "two thirds",
}
SPEECH_ML_PATTERN: str = r"(\d+(?:\.\d+)?)\s*ml\b"
SPEECH_ML_REPLACEMENT: str = r"\1 milliliters"
SPEECH_CL_PATTERN: str = r"(\d+(?:\.\d+)?)\s*cl\b"
SPEECH_CL_REPLACEMENT: str = r"\1 centiliters"
SPEECH_OZ_PATTERN: str = r"(\d+(?:\.\d+)?)\s*oz\b"
SPEECH_OZ_REPLACEMENT: str = r"\1 ounces"
SPEECH_NUMBER_RANGE_PATTERN: str = r"(\d+)\s*-\s*(\d+)"
SPEECH_NUMBER_RANGE_REPLACEMENT: str = r"\1 to \2"
SPEECH_CELSIUS_PATTERN: str = r"(\d+)\s*°\s*C"
SPEECH_CELSIUS_REPLACEMENT: str = r"\1 degrees Celsius"
SPEECH_SENTENCE_SPLIT_PATTERN: str = r"(?<=[.!?])\s+"

# TTS
TTS_VOICE: str = "en-GB-RyanNeural"
TTS_RATE: str = "-4%"
TTS_PITCH: str = "-2Hz"
TTS_POLL_INTERVAL_MS: int = 50
TTS_PIPELINE_QUEUE_SIZE: int = 2
TTS_INTER_SENTENCE_SILENCE_MS: int = 120
TTS_AUDIO_BLOCK_FRAMES: int = 512
TTS_AMPLITUDE_NORMALIZATION_PEAK: float = 6000.0

# MANIM RENDER
MANIM_OUTPUT_DIR: str = "output"
MANIM_TEMP_DIR_PREFIX: str = "media_temp_"
MANIM_QUALITY: str = "low_quality"
MANIM_VERBOSITY: str = "ERROR"
MANIM_VIDEO_EXTENSION: str = ".mp4"

# COCKTAIL ANIMATION
ANIM_ML_TO_HEIGHT_SCALE: float = 0.02

ANIM_CONTAINER_SHAKER_W_TOP: float = 2.2
ANIM_CONTAINER_SHAKER_W_BOT: float = 1.7
ANIM_CONTAINER_SHAKER_HEIGHT: float = 3.4
ANIM_CONTAINER_MIXING_W_TOP: float = 2.3
ANIM_CONTAINER_MIXING_W_BOT: float = 2.0
ANIM_CONTAINER_MIXING_HEIGHT: float = 3.2
ANIM_CONTAINER_STEMMED_W_TOP: float = 2.8
ANIM_CONTAINER_STEMMED_W_BOT: float = 0.4
ANIM_CONTAINER_STEMMED_HEIGHT: float = 1.8
ANIM_CONTAINER_TALL_W_TOP: float = 1.8
ANIM_CONTAINER_TALL_W_BOT: float = 1.6
ANIM_CONTAINER_TALL_HEIGHT: float = 3.6
ANIM_CONTAINER_ROCKS_W_TOP: float = 2.4
ANIM_CONTAINER_ROCKS_W_BOT: float = 2.0
ANIM_CONTAINER_ROCKS_HEIGHT: float = 2.4
ANIM_CONTAINER_OUTLINE_STROKE_WIDTH: float = 4.0
ANIM_CONTAINER_STEM_LENGTH: float = 1.0
ANIM_CONTAINER_STEM_BASE_HALF_WIDTH: float = 0.8
ANIM_CONTAINER_LABEL_FONT_SIZE: int = 15
ANIM_CONTAINER_LABEL_BUFF: float = 0.25
ANIM_LAYER_DEFAULT_OPACITY: float = 0.92

ANIM_VESSEL_Y_OFFSET: float = 0.9
ANIM_VESSEL_PAIR_X_OFFSET: float = 2.5
ANIM_VESSEL_CREATE_RUN_TIME: float = 0.5

ANIM_TITLE_FONT_SIZE: int = 36
ANIM_TITLE_BUFF: float = 0.35
ANIM_COLOR_DEFAULT_INGREDIENT: str = "#FFFFFF"
ANIM_INGREDIENT_DOT_RADIUS: float = 0.06
ANIM_INGREDIENT_FONT_SIZE_NORMAL: int = 15
ANIM_INGREDIENT_FONT_SIZE_COMPACT: int = 13
ANIM_INGREDIENT_COMPACT_THRESHOLD: int = 6
ANIM_INGREDIENT_ENTRY_BUFF: float = 0.12
ANIM_INGREDIENT_LIST_BUFF_NORMAL: float = 0.14
ANIM_INGREDIENT_LIST_BUFF_COMPACT: float = 0.10
ANIM_INGREDIENT_PANEL_BUFF: float = 0.35

ANIM_STEP_WRAP_WORDS_PER_LINE: int = 6
ANIM_STEP_TITLE_FONT_SIZE: int = 25
ANIM_STEP_TITLE_Y: float = 2.1
ANIM_STEP_DESC_FONT_SIZE: int = 17
ANIM_STEP_DESC_LINE_SPACING: float = 1.1
ANIM_STEP_DESC_BUFF: float = 0.15
ANIM_STEP_TRANSFORM_RUN_TIME: float = 0.45

ANIM_CHILL_FROST_STROKE_WIDTH: float = 6.0
ANIM_CHILL_FROST_STROKE_OPACITY: float = 0.7
ANIM_CHILL_FADE_TARGET_OPACITY: float = 0.15

ANIM_COLOR_ICE: str = "#D4E6F1"
ANIM_ICE_STROKE_WIDTH: float = 1.5
ANIM_ICE_SPHERE_RADIUS: float = 0.45
ANIM_ICE_ROCK_SIZE: float = 0.9
ANIM_ICE_ROCK_CORNER_RADIUS: float = 0.1
ANIM_ICE_LARGE_FILL_OPACITY: float = 0.8
ANIM_ICE_LARGE_Y_OFFSET: float = 0.5
ANIM_ICE_LARGE_HEIGHT_DELTA: float = 0.95
ANIM_ICE_CUBE_COUNT_PREP: int = 3
ANIM_ICE_CUBE_COUNT_SERVING: int = 2
ANIM_ICE_CUBE_SIZE: float = 0.42
ANIM_ICE_CUBE_CORNER_RADIUS: float = 0.08
ANIM_ICE_CUBE_FILL_OPACITY: float = 0.85
ANIM_ICE_CUBE_X_SPACING: float = 0.35
ANIM_ICE_CUBE_Y_OFFSET: float = 0.25
ANIM_ICE_CUBE_HEIGHT_DELTA: float = 0.45
ANIM_SOLIDS_Z_INDEX: int = 10


ANIM_COLOR_DEFAULT_LIQUID: str = "#E9F1F5"
ANIM_MEASURE_DEFAULT_AMOUNT_ML: float = 20.0
ANIM_MEASURE_DASH_HEIGHT_SCALE: float = 0.03
ANIM_MEASURE_MAX_FILL_MARGIN: float = 0.15
ANIM_MEASURE_MIN_AVAILABLE_HEIGHT: float = 0.1
ANIM_MEASURE_TOP_MARGIN: float = 0.20
ANIM_MEASURE_TOP_MIN_THICKNESS: float = 0.4
ANIM_MEASURE_FALLBACK_THICKNESS: float = 0.4
ANIM_MEASURE_STREAM_START_OFFSET: float = 1.2
ANIM_MEASURE_STREAM_STROKE_WIDTH_LIQUID: float = 3.5
ANIM_MEASURE_STREAM_STROKE_WIDTH_OTHER: float = 2.0
ANIM_MEASURE_STREAM_Z_INDEX: int = 5
ANIM_SOLID_LEAF_WIDTH: float = 0.4
ANIM_SOLID_LEAF_HEIGHT: float = 0.22
ANIM_SOLID_LEAF_FILL_OPACITY: float = 0.9
ANIM_SOLID_SQUARE_SIDE: float = 0.32
ANIM_SOLID_SQUARE_FILL_OPACITY: float = 0.95
ANIM_SOLID_STROKE_WIDTH: float = 1.0
ANIM_SOLID_Y_OFFSET: float = 0.2
ANIM_SOLID_HEIGHT_DELTA: float = 0.35

ANIM_COLOR_DEFAULT_SHAKE_BLEND: str = "#E59866"
ANIM_SHAKE_WIGGLE_ROTATION: float = 0.12
ANIM_SHAKE_WIGGLE_COUNT: int = 6
ANIM_SHAKE_WIGGLE_RUN_TIME: float = 1.0

ANIM_COLOR_DEFAULT_MUDDLE_BLEND: str = "#C86D27"
ANIM_COLOR_MUDDLER_WOOD_DARK: str = "#5D4037"
ANIM_COLOR_MUDDLER_WOOD_DARKEST: str = "#3E2723"
ANIM_COLOR_MUDDLER_WOOD_LIGHT: str = "#795548"
ANIM_COLOR_MUDDLER_WOOD_MEDIUM: str = "#4E342E"
ANIM_MUDDLER_HEAD_HEIGHT: float = 0.55
ANIM_MUDDLER_HEAD_WIDTH: float = 0.44
ANIM_MUDDLER_HEAD_CORNER_RADIUS: float = 0.06
ANIM_MUDDLER_STROKE_WIDTH: float = 1.5
ANIM_MUDDLER_HANDLE_WIDTH: float = 0.22
ANIM_MUDDLER_HANDLE_CORNER_RADIUS: float = 0.07
ANIM_MUDDLER_HANDLE_MIN_HEIGHT: float = 2.7
ANIM_MUDDLER_HANDLE_HEIGHT_PADDING: float = 0.8
ANIM_MUDDLER_POMMEL_RADIUS: float = 0.15
ANIM_TOOL_Z_INDEX: int = 15
ANIM_MUDDLE_MIN_HEIGHT: float = 0.25

ANIM_COLOR_DEFAULT_STIR_BLEND: str = "#C86D27"
ANIM_COLOR_SPOON_METAL_LIGHT: str = "#ECEFF1"
ANIM_COLOR_SPOON_METAL_DARK: str = "#90A4AE"
ANIM_COLOR_SPOON_INNER: str = "#CFD8DC"
ANIM_COLOR_SPOON_KNOB: str = "#B0BEC5"
ANIM_COLOR_SPOON_KNOB_STROKE: str = "#78909C"
ANIM_SPOON_BOWL_WIDTH: float = 0.28
ANIM_SPOON_BOWL_HEIGHT: float = 0.42
ANIM_SPOON_INNER_WIDTH: float = 0.18
ANIM_SPOON_INNER_HEIGHT: float = 0.30
ANIM_SPOON_INNER_OPACITY: float = 0.6
ANIM_SPOON_KNOB_RADIUS: float = 0.09
ANIM_SPOON_STROKE_WIDTH: float = 1.5
ANIM_SPOON_STEM_STROKE_WIDTH: float = 3.5
ANIM_SPOON_STEM_HEIGHT_PADDING: float = 1.0
ANIM_SPOON_SPIRAL_COUNT: int = 6
ANIM_SPOON_SPIRAL_MARGIN: float = 0.4
ANIM_SPOON_SPIRAL_X_OFFSET: float = 0.04
ANIM_SPOON_SPIRAL_Y_STEP: float = 0.08
ANIM_STIR_ORBIT_RADIUS_RATIO: float = 0.22
ANIM_STIR_ORBIT_RY: float = 0.04
ANIM_STIR_ORBIT_Y_OFFSET: float = 0.18
ANIM_STIR_ORBIT_ANGLE_PI_MULTIPLIER: float = 4.0
ANIM_STIR_ORBIT_RUN_TIME: float = 1.4
ANIM_STIR_SOLIDS_ROTATE: float = 0.3

ANIM_COLOR_DEFAULT_STRAIN: str = "#E59866"
ANIM_COLOR_FOAM: str = "#FFFFFF"
ANIM_STRAIN_RIM_MARGIN: float = 0.15
ANIM_STRAIN_FOAM_THICKNESS: float = 0.45
ANIM_STRAIN_FOAM_MIN_LIQUID_THICKNESS: float = 0.6
ANIM_STRAIN_TILT_ANGLE: float = 0.42
ANIM_STRAIN_TILT_RUN_TIME: float = 0.45
ANIM_STRAIN_POUR_STROKE_WIDTH: float = 4.5
ANIM_STRAIN_FOAM_Z_INDEX: int = 13
ANIM_STRAIN_TRANSFER_RUN_TIME: float = 0.75
ANIM_STRAIN_TILT_BACK_RUN_TIME: float = 0.40

ANIM_COLOR_DEFAULT_GARNISH: str = "#FFA500"
ANIM_GARNISH_DEFAULT_SHAPE: str = "half circle"
ANIM_GARNISH_STROKE_WIDTH: float = 1.0
ANIM_GARNISH_LEAF_WIDTH: float = 0.42
ANIM_GARNISH_LEAF_HEIGHT: float = 0.22
ANIM_GARNISH_HALF_CIRCLE_INNER_RADIUS: float = 0.15
ANIM_GARNISH_HALF_CIRCLE_OUTER_RADIUS: float = 0.38
ANIM_GARNISH_TRIANGLE_SCALE: float = 0.25
ANIM_GARNISH_DASH_RADIUS: float = 0.08
ANIM_GARNISH_DASH_BUFF: float = 0.12
ANIM_GARNISH_FOAM_HEIGHT: float = 0.2
ANIM_GARNISH_FOAM_WIDTH_RATIO: float = 0.85
ANIM_GARNISH_FOAM_OPACITY: float = 0.95
ANIM_GARNISH_SURFACE_Y_OFFSET: float = 0.1
ANIM_GARNISH_SIDE_OFFSET: float = 0.45
ANIM_GARNISH_Z_INDEX: int = 20
ANIM_GARNISH_FADE_RUN_TIME: float = 0.4

ANIM_DEFAULT_STEP_WAIT_S: float = 0.4
ANIM_FINAL_WAIT_S: float = 1.5

ANIM_DEFAULT_COCKTAIL_NAME: str = "Cocktail"
ANIM_DEFAULT_GLASS_TYPE: str = "rocks"
ANIM_LABEL_SERVING_GLASS: str = "Serving Glass"
ANIM_LABEL_SHAKER: str = "Shaker"
ANIM_LABEL_MIXING_GLASS: str = "Mixing Glass"

ANIM_TITLE_FADE_SHIFT: float = 0.3
ANIM_TITLE_FADE_RUN_TIME: float = 0.5
ANIM_INGREDIENT_LIST_FADE_SHIFT: float = 0.3
ANIM_INGREDIENT_LIST_FADE_RUN_TIME: float = 0.6

ANIM_CHILL_FADE_IN_RUN_TIME: float = 0.4
ANIM_CHILL_FADE_OUT_RUN_TIME: float = 0.3

ANIM_ICE_LARGE_FADE_SHIFT: float = 0.8
ANIM_ICE_LARGE_FADE_RUN_TIME: float = 0.35
ANIM_ICE_CUBE_FADE_SHIFT: float = 0.6
ANIM_ICE_CUBE_FADE_RUN_TIME: float = 0.25

ANIM_MEASURE_STREAM_CREATE_RUN_TIME: float = 0.20
ANIM_MEASURE_LAYER_FADE_SHIFT: float = 0.05
ANIM_MEASURE_LAYER_FADE_RUN_TIME: float = 0.35
ANIM_MEASURE_STREAM_FADE_RUN_TIME: float = 0.15
ANIM_SOLID_FADE_SHIFT: float = 0.8
ANIM_SOLID_FADE_RUN_TIME: float = 0.35

ANIM_SHAKE_WIGGLE_SCALE: float = 1.0
ANIM_SHAKE_MERGE_RUN_TIME: float = 0.45

ANIM_MUDDLER_GROOVE_INSET: float = 0.05
ANIM_MUDDLER_GROOVE_DROP: float = 0.08
ANIM_MUDDLER_HANDLE_OVERLAP: float = 0.08
ANIM_MUDDLER_POMMEL_OVERLAP: float = 0.06
ANIM_MUDDLER_BOTTOM_OFFSET: float = 0.05
ANIM_MUDDLER_FADE_IN_SHIFT: float = 1.0
ANIM_MUDDLER_FADE_IN_RUN_TIME: float = 0.35
ANIM_MUDDLER_FADE_OUT_SHIFT: float = 0.9
ANIM_MUDDLER_FADE_OUT_RUN_TIME: float = 0.3
ANIM_MUDDLER_STROKE_RUN_TIME: float = 0.25
ANIM_MUDDLER_STROKES: tuple[tuple[float, float], ...] = ((-0.05, 0.20), (0.15, -0.40), (-0.10, 0.20))
ANIM_MUDDLE_MERGE_RUN_TIME: float = 0.40

ANIM_SPOON_INNER_X_SHIFT: float = 0.03
ANIM_SPOON_KNOB_STROKE_WIDTH: float = 1.0
ANIM_SPOON_FADE_IN_SHIFT: float = 0.8
ANIM_SPOON_FADE_IN_RUN_TIME: float = 0.35
ANIM_SPOON_FADE_OUT_SHIFT: float = 0.8
ANIM_SPOON_FADE_OUT_RUN_TIME: float = 0.25
ANIM_STIR_MERGE_RUN_TIME: float = 0.40

ANIM_STRAIN_FOAM_OPACITY: float = 1.0
ANIM_STRAIN_LAYER_FADE_SHIFT: float = 0.15
ANIM_STRAIN_FOAM_FADE_SHIFT: float = 0.12
ANIM_STRAIN_POUR_CREATE_RUN_TIME: float = 0.20
ANIM_STRAIN_POUR_FADE_RUN_TIME: float = 0.15
ANIM_STRAIN_POUR_START_OFFSET: tuple[float, float] = (0.05, -0.05)
ANIM_STRAIN_POUR_CONTROL_1_OFFSET: tuple[float, float] = (0.55, 0.35)
ANIM_STRAIN_POUR_CONTROL_2_OFFSET: tuple[float, float] = (-0.45, 0.65)

ANIM_GARNISH_FOAM_CORNER_RADIUS: float = 0.1
ANIM_GARNISH_FADE_SHIFT: float = 0.3

ANIM_FINALE_FADE_RUN_TIME: float = 0.4


# PHONE SCAN SERVER
PHONE_SCAN_PORT: int = 8080
PHONE_SCAN_UPLOAD_DIR: str = "output"
PHONE_SCAN_HTML_FILENAME: str = "scan_phone.html"
PHONE_SCAN_POLL_INTERVAL_S: float = 0.1

PHONE_SCAN_WINDOW_TITLE: str = "Lloyd — Wi-Fi Mobile Transmitter Receiver"
PHONE_SCAN_WINDOW_WIDTH: int = 850
PHONE_SCAN_WINDOW_HEIGHT: int = 520

PHONE_SCAN_MAIN_MARGIN: int = 24
PHONE_SCAN_MAIN_SPACING: int = 20
PHONE_SCAN_PANEL_MARGIN: int = 20
PHONE_SCAN_PANEL_BORDER_RADIUS: int = 8

PHONE_SCAN_QR_BOX_SIZE: int = 6
PHONE_SCAN_QR_BORDER: int = 2
PHONE_SCAN_QR_FILL_COLOR: str = "black"
PHONE_SCAN_QR_BACK_COLOR: str = "white"

PHONE_SCAN_PANEL_BG: str = "#121824"
PHONE_SCAN_PANEL_BORDER: str = "#1f2d47"
PHONE_SCAN_SUBTEXT_COLOR: str = "#90A4AE"
PHONE_SCAN_URL_TEXT_COLOR: str = "#ECEFF1"
PHONE_SCAN_PREVIEW_PLACEHOLDER_COLOR: str = "#546E7A"

PHONE_SCAN_TITLE_FONT_SIZE: int = 16
PHONE_SCAN_INSTRUCTIONS_FONT_SIZE: int = 12
PHONE_SCAN_URL_FONT_SIZE: int = 13
PHONE_SCAN_STATUS_FONT_SIZE: int = 14
PHONE_SCAN_PREVIEW_FONT_SIZE: int = 14

PHONE_SCAN_TITLE_TEXT: str = "MOBILE BAR SCANNER"
PHONE_SCAN_INSTRUCTIONS_TEXT: str = "Scan with phone camera while on the same Wi-Fi:"
PHONE_SCAN_STATUS_WAITING_TEXT: str = "LATEST SCAN: WAITING FOR PHOTO"
PHONE_SCAN_PREVIEW_PLACEHOLDER_TEXT: str = "No snapshot received yet"
PHONE_SCAN_CANCELLED_MESSAGE: str = "Scan cancelled before a photo was received."

# AGENT
MCP_SERVER_NAME: str = "bartender"
AGENT_MCP_SERVER_VERSION: str = "1.0.0"
AGENT_MODEL: str = "claude-opus-5"
AGENT_PERMISSION_MODE: str = "bypassPermissions"
AGENT_SYSTEM_PROMPT_PATH: str = "prompts/SYSTEM_PROMPT.md"
AGENT_SCAN_PROMPT_PATH: str = "prompts/SCAN_PROMPT.md"
AGENT_SCAN_DEFAULT_MEDIA_TYPE: str = "image/jpeg"
AGENT_ENV: dict[str, str] = {"ENABLE_TOOL_SEARCH": "false"}

AGENT_TOOL_RENDER_ANIMATION: str = "render_animation"
AGENT_TOOL_SHOW_RECIPE: str = "show_recipe"
AGENT_TOOL_SCAN_SHELF: str = "scan_shelf"
AGENT_TOOL_WEB_SEARCH: str = "web_search"
AGENT_TOOL_NAMES: tuple[str, ...] = (
    AGENT_TOOL_RENDER_ANIMATION,
    AGENT_TOOL_SHOW_RECIPE,
    AGENT_TOOL_SCAN_SHELF,
    AGENT_TOOL_WEB_SEARCH,
)
AGENT_ALLOWED_TOOLS: tuple[str, ...] = tuple(
    f"mcp__{MCP_SERVER_NAME}__{name}" for name in AGENT_TOOL_NAMES
)

AGENT_DESC_RENDER_ANIMATION: str = (
    "Play the step-by-step build animation for one cocktail on the user's screen. "
    "Call this AFTER you have already written your spoken reply as plain text, and "
    "only once per named cocktail. The spec is the COMPLETE build for the whole "
    "drink, not just the step you are currently narrating. The first step must "
    "always be a chill action with target serving_glass and a glass matching "
    "glass_type."
)
AGENT_DESC_SHOW_RECIPE: str = (
    "Display the recipe card for one named cocktail. Call this AFTER you have "
    "already written your spoken reply as plain text. Use it when the user asks "
    "what is in a drink or asks for its recipe, rather than asking to be walked "
    "through building it."
)
AGENT_DESC_SCAN_SHELF: str = (
    "Open the phone camera popup, wait for the user to photograph their bar shelf, "
    "and return the list of bottles identified in the photo. Call this ONLY when "
    "the user explicitly asks you to scan, look at, or check the shelf or the "
    "counter. Never call it for a vague or general question -- it costs the user "
    "several seconds and a photo."
)
AGENT_DESC_WEB_SEARCH: str = (
    "Search the web and return raw results. Use this ONLY for genuinely current or "
    "obscure information you do not already know, such as a bar that opened this "
    "year or a product that may have been discontinued. Do NOT use it for classic "
    "cocktails, standard technique, bar terminology, cocktail history, or "
    "suggesting drinks from a list of bottles -- answer those directly."
)

AGENT_TOOL_RESULT_ANIMATION: str = "Animation started."
AGENT_TOOL_RESULT_RECIPE: str = "Recipe card shown."
AGENT_TOOL_ERROR_ANIMATION_SCHEMA: str = "The animation spec was rejected by the schema:"
AGENT_TOOL_ERROR_SCAN: str = "The shelf scan failed:"
AGENT_TOOL_ERROR_SCAN_EMPTY: str = "The photo arrived but no bottles could be identified in it."
AGENT_TOOL_ERROR_WEB_SEARCH: str = "The web search failed:"
AGENT_SCAN_NO_RESULT: str = "No photo was received."

AGENT_ERROR_SPEECH: str = "Something went wrong on my end -- would you like to try that again?"
AGENT_NOT_READY_SPEECH: str = "Give me a second -- I'm still waking up."
AGENT_RENDER_STATUS_TEXT: str = "Render completed"
AGENT_RENDER_STARTED_TEXT: str = "Creating your cocktail video..."
AGENT_RENDER_FAILED_PREFIX: str = "Rendering failed:"

STEP_BY_STEP_DEBUG_DIR: str = "runtime/step_by_step_debug"
STEP_BY_STEP_RERENDER_KEYWORDS: tuple[str, ...] = (
    "rerender", "re-render", "renew", "regenerate", "redo", "recreate",
)

WEB_SEARCH_MAX_RESULTS: int = 5
WEB_SEARCH_CACHE_SIZE: int = 32

# PERFORMANCE INSTRUMENTATION
PERF_ENABLED: bool = True
PERF_LOG_TO_FILE: bool = True
PERF_LOG_DIR: str = "runtime/perf"
PERF_LOG_FILENAME_FORMAT: str = "%Y%m%d.jsonl"
PERF_LOG_PREFIX: str = "[perf]"
PERF_STAGE_COLUMN_WIDTH: int = 28




# THREAD DIAGNOSTICS
QTHREAD_DIAGNOSTICS_ENABLED: bool = True
QTHREAD_LOG_PREFIX: str = "[Lloyd thread]"
SHUTDOWN_THREAD_TIMEOUT_MS: int = 3000